### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by duoduo1234** [KAKAFEI123/DsDTW#2]
can you upload the code preparing for dataset?it is as the input for the model.Thank you!

**Comment by duoduo1234** [comment]
because i don't have MCYT 100 dataset, and plan to use other dataset to replace it.

**Comment by KAKAFEI123** [comment]
Sorry，you need to do this part yourself.

**Comment by duoduo1234** [comment]
yes,you are right.I am a Beginner, so i need your advises.

**Comment by duoduo1234** [comment]
it's like this:{45: {True: [...], False: [...]}. it can run, but i don't know if the result of train is right,and i will be check.
i have a question,why only three keys are used?just x, y, pressure,  what about other keys?

**Comment by KAKAFEI123** [comment]
In our study, x, y and pressure are used to supply 12 time funtions (see our paper) as the inputs of DsDTW.  Please consider to star our project and cite our paper if you find the code useful. Note that this code is free to the academic community for research purpose only.

**Comment by duoduo1234** [comment]
Thank you for reply. I stared already.I mean dataset's other original key is not used,maybe because they're incrorrect.




??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KAKAFEI123/DsDTW"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月4日(星期四) 晚上6:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KAKAFEI123/DsDTW] about data (Issue #2)





 
In our study, x, y and pressure are used to supply 12 time funtions (see our paper) as the inputs of DsDTW.  Please consider to star our project and cite our paper if you find the code useful. Note that this code is free to the academic community for research purpose only.

**Comment by KAKAFEI123** [comment]
According to our experiments, x, y and pressure are critical to extracting discriminative features for verification. Of course, you can try the rest keys and test their effectiveness.
