### ISSUE TITLE
关于时间的小疑问 

### ISSUE THREAD

**Issue by budaLi** [KAKAFEI123/DsDTW#3]
您好，非常感谢您的开源。
想请教下您的论文中提到50个batch " it takes as long as 17.26 seconds and 16.22 seconds
for TA-RNN and deep DTW to accomplish verification,
respectively."   
后续又提到"Specifi-
cally, it takes 8 milliseconds for our DsDTW to verify a sig-
nature pair,"  
有点不太理解这个时间是怎么测试得出的。

**Comment by yo-WASSUP** [comment]
请问论文是怎么获取的呢？
